import os
import requests

# Securely fetch keys from the GitHub environment
GEMINI_API_KEY = os.environ.get("G_STUDIO_LINKEDIN_POSTING_API")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO = os.environ.get("GITHUB_REPOSITORY")

# 1. Ask Gemini to draft the post WITH GOOGLE SEARCH GROUNDING
url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
headers = {'Content-Type': 'application/json'}

prompt = "Search the web for a major, factual advancement in quantum computing from the past 7 days. Write a highly technical but accessible LinkedIn post for C-suite executives. You MUST include the exact URLs of your sources at the end of the post."

data = {
    "contents": [{"parts":[{"text": prompt}]}],
    "tools": [{"googleSearch": {}}] # Forces factual web grounding
}

response = requests.post(url, headers=headers, json=data)
post_content = response.json()['candidates'][0]['content']['parts'][0]['text']

# 2. Fetch a high-quality, real image of quantum hardware from Unsplash
# Note: Ensure you add UNSPLASH_ACCESS_KEY to your GitHub Secrets as well
unsplash_url = f"https://api.unsplash.com/photos/random?query=quantum+computing+hardware&client_id={os.environ.get('UNSPLASH_ACCESS_KEY')}"
image_response = requests.get(unsplash_url)
image_url = image_response.json()['urls']['regular']

# 3. Create a GitHub Issue for your review
issue_url = f"https://api.github.com/repos/{REPO}/issues"
issue_headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
issue_data = {
    "title": "LinkedIn Draft for Approval",
    "body": f"Here is the factual draft generated by Gemini:\n\n![Quantum Hardware]({image_url})\n\n---\n\n{post_content}\n\n---\n\n**To publish:** Reply to this issue with the exact word `Approve`.",
    "labels": ["linkedin-draft"]
}

requests.post(issue_url, headers=issue_headers, json=issue_data)
print("Factual draft sent to GitHub Issues successfully.")