import os
import requests

GEMINI_API_KEY = os.environ.get("G_STUDIO_LINKEDIN_POSTING_API")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO = os.environ.get("GITHUB_REPOSITORY")

# 1. Ask Gemini to draft the post WITH GOOGLE SEARCH GROUNDING
url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
headers = {'Content-Type': 'application/json'}

prompt = """Search the web for a major, factual advancement in quantum computing from the past 7 days. 
Write a highly technical but accessible LinkedIn post for C-suite executives. 
CRITICAL CONSTRAINTS:
1. The post body MUST be strictly under 1600 characters. Be concise and authoritative.
2. After the post body, you MUST type the exact text '---SOURCES---' on a new line.
3. Below '---SOURCES---', list the exact URLs of your research."""

data = {
    "contents": [{"parts":[{"text": prompt}]}],
    "tools": [{"googleSearch": {}}]
}

# Call Gemini API with a 50-second timeout
response = requests.post(url, headers=headers, json=data, timeout=50)
post_content = response.json()['candidates'][0]['content']['parts'][0]['text']

# 2. Create a GitHub Issue for your review
issue_url = f"https://api.github.com/repos/{REPO}/issues"
issue_headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
issue_data = {
    "title": "LinkedIn Draft for Approval",
    "body": f"Here is the factual draft generated by Gemini:\n\n---\n\n{post_content}\n\n---\n\n**To publish:** Reply to this issue with the exact word `Approve`.",
    "labels": ["linkedin-draft"]
}

# Send to GitHub with a 50-second timeout
requests.post(issue_url, headers=issue_headers, json=issue_data, timeout=50)
print("Factual draft sent to GitHub Issues successfully.")