import os
import requests

GEMINI_API_KEY = os.environ.get("G_STUDIO_LINKEDIN_POSTING_API")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO = os.environ.get("GITHUB_REPOSITORY")

# 1. Ask Gemini to draft the post WITH GOOGLE SEARCH GROUNDING
url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={GEMINI_API_KEY}"
headers = {'Content-Type': 'application/json'}

prompt = """Search the web for a major, factual advancement in quantum computing from the past 7 days. 
Write a highly technical but accessible LinkedIn post tailored for C-suite executives overseeing R&D, Deep-Tech, and Strategic Innovation. 

CRITICAL CONSTRAINTS:
1. TONE & STYLE: Write in a grounded, authoritative, and humanised voice using British English spelling. STRICT BAN on AI buzzwords, clichéd transitions, and fluff (e.g., absolutely do not use "delve," "game-changer," "tapestry," "revolutionary," or "in today's rapidly evolving landscape"). State the facts cleanly.
2. NO EMAIL FORMATTING: Do NOT use "Subject:" or "Title:". Start directly with a bold, one-sentence executive hook.
3. LENGTH: The post body MUST be strictly under 2000 characters. Break up long paragraphs for easy mobile reading.
4. THE SIGN-OFF: At the very end of the post, you MUST include this exact call-to-action:
   "Stay tuned follow QuantumBeads for weekly enterprise intelligence."
5. HASHTAGS: Include exactly 3 high-level hashtags below the sign-off (e.g., #QuantumComputing #DeepTech #EnterpriseStrategy).
6. CITATION DIVIDER: Immediately after the hashtags, you MUST type the exact text '---SOURCES---' on a new line.
7. THE SOURCES: Below '---SOURCES---', list the Publication Name, Article Title, Date, and clean root domain (e.g., 'IBM Research (ibm.com)'). STRICT BAN: Do not output any 'vertexaisearch' or 'google' redirect URLs."""

data = {
    "contents": [{"parts":[{"text": prompt}]}],
    "tools": [{"googleSearch": {}}]
}

# Call Gemini API with a 50-second timeout
response = requests.post(url, headers=headers, json=data, timeout=50)
post_content = response.json()['candidates'][0]['content']['parts'][0]['text']

# 2. Create a GitHub Issue for your review
issue_url = f"https://api.github.com/repos/{REPO}/issues"
issue_headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
issue_data = {
    "title": "LinkedIn Draft for Approval",
    "body": f"Here is the factual draft generated by Gemini:\n\n---\n\n{post_content}\n\n---\n\n**To publish:** Assign the `Approved` label to this issue. The Tuesday automated queue will handle the rest.",
    "labels": ["linkedin-draft"]
}

# Send to GitHub with a 50-second timeout
requests.post(issue_url, headers=issue_headers, json=issue_data, timeout=50)
print("Factual draft sent to GitHub Issues successfully.")