import os
import requests
import sys

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO = os.environ.get("GITHUB_REPOSITORY")
ACCESS_TOKEN = os.environ.get("LINKEDIN_ACCESS_TOKEN")
ORG_ID = os.environ.get("LINKEDIN_ORG_ID", "").strip()

print("--- INITIATING TUESDAY QUEUE SCAN ---")

# 1. Search GitHub for the Approved Draft
issues_url = f"https://api.github.com/repos/{REPO}/issues"
headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github.v3+json"
}
params = {
    "state": "open",
    "labels": "Approved"
}

response = requests.get(issues_url, headers=headers, params=params, timeout=30)
issues = response.json()

if not issues:
    print("No approved drafts found in the queue. The machine will sleep until next Tuesday.")
    sys.exit(0)

# Grab the first approved issue in the queue
target_issue = issues[0]
issue_number = target_issue['number']
issue_body = target_issue['body']

print(f"Found Approved Draft: Issue #{issue_number}")

# 2. Extract the Executive Text and Sever the Citations
try:
    parts = issue_body.split("---")
    if len(parts) >= 3:
        raw_draft = "---".join(parts[1:-1]).strip()
    else:
        raw_draft = issue_body.strip()
        
    if "---SOURCES---" in raw_draft:
        clean_text = raw_draft.split("---SOURCES---")[0].strip()
    else:
        clean_text = raw_draft
        
    # Remove any residual introductory text
    clean_text = clean_text.replace("Here is the factual draft generated by Gemini:", "").strip()
except Exception:
    clean_text = issue_body.strip()

if not clean_text:
    print("Error: Extracted text is empty. Aborting publish.")
    sys.exit(1)

# 3. Push to the QuantumBeads LinkedIn Page
print(f"Targeting Company Page URN: urn:li:organization:{ORG_ID}")
linkedin_url = "https://api.linkedin.com/rest/posts"
linkedin_headers = {
    "Authorization": f"Bearer {ACCESS_TOKEN}",
    "LinkedIn-Version": "202602", 
    "X-Restli-Protocol-Version": "2.0.0",
    "Content-Type": "application/json"
}

post_data = {
    "author": f"urn:li:organization:{ORG_ID}",
    "commentary": clean_text,
    "visibility": "PUBLIC",
    "distribution": {
        "feedDistribution": "MAIN_FEED",
        "targetEntities": [],
        "thirdPartyDistributionChannels": []
    },
    "lifecycleState": "PUBLISHED",
    "isResreshareDisabledByAuthor": False
}

li_response = requests.post(linkedin_url, headers=linkedin_headers, json=post_data, timeout=30)

if li_response.status_code == 201:
    print("✅ Successfully published to the QuantumBeads Company Page!")
    
    # 4. Close the Issue to Keep the Control Room Clean
    issue_update_url = f"https://api.github.com/repos/{REPO}/issues/{issue_number}"
    requests.patch(issue_update_url, headers=headers, json={"state": "closed"}, timeout=30)
    requests.post(f"{issue_update_url}/comments", headers=headers, json={"body": "✅ Successfully published to the QuantumBeads Company feed by the Tuesday automated queue."}, timeout=30)
else:
    print(f"Failed to post. Status code: {li_response.status_code}")
    print(li_response.text)
    sys.exit(1)